// Sample BSIT Curriculum Data from WMSU
// This serves as a template for other engineering programs

export const BSIT_CURRICULUM = {
  id: "CURR-BSIT-2023-2024",
  title: "Bachelor of Science in Information Technology (BSIT)",
  program: "Information Technology",
  academicYear: "2023-2024",
  institution: "Western Mindanao State University",
  totalUnits: 152,
  status: "Published",
  programs: ["Computer Engineering", "Information Technology"],
  createdAt: new Date().toISOString(),
  approvedBy: "admin",
  approvedAt: new Date().toISOString(),
  versions: [],
  attachments: [],
  courses: [
    // FIRST YEAR - FIRST SEMESTER
    {
      code: "CC 100",
      title: "Introduction to Computing",
      semester: "1Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "None",
      description:
        "Overview of computers, number systems, digital logic, assembly language, and operating systems",
    },
    {
      code: "CC 101",
      title: "Computer Programming 1 (Fundamentals of Programming)",
      semester: "1Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "None",
      description:
        "Fundamental programming concepts using C/C++, control structures, and problem-solving",
    },
    {
      code: "CAS 101",
      title: "Purposive Communication",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Writing, speaking, and presenting to different audiences for various purposes",
    },
    {
      code: "MATH 100",
      title: "Mathematics in the Modern World",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Nature of mathematics, practical applications, and intellectual dimensions",
    },
    {
      code: "US 101",
      title: "Understanding the Self",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Nature of identity, factors affecting personal development and maintenance",
    },
    {
      code: "GE Elect 1",
      title: "General Education Elective 1",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Choose from: Environmental Science, Philippine Indigenous Communities, Gender & Society, etc.",
    },
    {
      code: "PATHFit 1",
      title: "Movement and Competency Training",
      semester: "1Y-1S",
      units: 2,
      lec: 2,
      lab: 0,
      type: "Mandated",
      prerequisites: "None",
      description: "Fundamental movement patterns and functional fitness",
    },
    {
      code: "NSTP 1",
      title: "National Service Training Program I",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Mandated",
      prerequisites: "None",
      description:
        "CWTS 1/LTS 1/ROTC 1 - Physical, moral, spiritual development",
    },
    {
      code: "FIL 101",
      title: "Wika, Kultura, at Mapayapang Lipunan",
      semester: "1Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Institutional",
      prerequisites: "None",
      description: "Filipino language, culture, and society",
    },

    // FIRST YEAR - SECOND SEMESTER
    {
      code: "IT 121",
      title: "Discrete Mathematics",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Professional",
      prerequisites: "MATH 100",
      description:
        "Discrete structures, functions, sets, relations, basic logic, graphs and trees",
    },
    {
      code: "IT 122",
      title: "Introduction to Human-Computer Interaction",
      semester: "1Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 100",
      description:
        "Way people interact with technology, usability principles in design",
    },
    {
      code: "CC 102",
      title: "Computer Programming 2 (Intermediate Programming)",
      semester: "1Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 101",
      description:
        "Data structures, object-oriented programming concepts using C/C++",
    },
    {
      code: "HIST 100",
      title: "Life and Works of Rizal",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Study of Dr. Jose P. Rizal and his role in Filipino nation-building",
    },
    {
      code: "A&H 100",
      title: "Art Appreciation",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Nature, function, and appreciation of the arts in contemporary society",
    },
    {
      code: "GE Elect 2",
      title: "General Education Elective 2",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description: "Choose from elective courses",
    },
    {
      code: "PATHFit 2",
      title: "Exercise-based Fitness Activities",
      semester: "1Y-2S",
      units: 2,
      lec: 2,
      lab: 0,
      type: "Mandated",
      prerequisites: "PATHFit 1",
      description: "Exercise programs for fitness and wellness",
    },
    {
      code: "NSTP 2",
      title: "National Service Training Program II",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Mandated",
      prerequisites: "NSTP 1",
      description: "CWTS 2/LTS 2/ROTC 2 - Community engagement",
    },
    {
      code: "PHILCON",
      title: "Philippine Constitution",
      semester: "1Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Institutional",
      prerequisites: "None",
      description:
        "Political science, governance, executive/legislative/judicial branches",
    },

    // SECOND YEAR - FIRST SEMESTER
    {
      code: "IT Elective 1",
      title: "IT Professional Elective 1",
      semester: "2Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "None",
      description:
        "Choose from: Human-Computer Interaction 2, Object-Oriented Programming, Web Systems, Platform Technologies, Systems Integration 2, or Integrative Programming 2",
    },
    {
      code: "IT 212",
      title: "Quantitative Methods",
      semester: "2Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Professional",
      prerequisites: "IT 121",
      description:
        "Discrete mathematics, logical and mathematical thinking for computer science",
    },
    {
      code: "IT 213",
      title: "Social and Professional Practice",
      semester: "2Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Professional",
      prerequisites: "None",
      description:
        "Ethical history, philosophies, and ethical issues in business and information systems",
    },
    {
      code: "CC 103",
      title: "Data Structures and Algorithms",
      semester: "2Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 102",
      description:
        "Lists, stacks, queues, trees, graphs, sorting and searching algorithms",
    },
    {
      code: "CC 104",
      title: "Information Management",
      semester: "2Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 102",
      description:
        "Database management system concepts, relational algebra, SQL",
    },
    {
      code: "HIST 101",
      title: "Readings in Philippine History",
      semester: "2Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Philippine history through selected primary sources and analysis",
    },
    {
      code: "STS 100",
      title: "Science, Technology and Society",
      semester: "2Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Interactions between science/technology and social, cultural, political contexts",
    },
    {
      code: "PATHFit 3",
      title:
        "Dance 1/Sports 1/Martial Arts 1/Group Exercise 1/Outdoor Activities 1",
      semester: "2Y-1S",
      units: 2,
      lec: 2,
      lab: 0,
      type: "Mandated",
      prerequisites: "PATHFit 1, PATHFit 2",
      description: "Choice-based fitness and wellness activities",
    },

    // SECOND YEAR - SECOND SEMESTER
    {
      code: "IT 221",
      title: "Integrative Programming and Technologies 1",
      semester: "2Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 103",
      description:
        "Advanced database management systems design and implementation",
    },
    {
      code: "IT 222",
      title: "Networking 1",
      semester: "2Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 100",
      description:
        "Fundamental concepts on data communication and computer network design",
    },
    {
      code: "IT Elective 2",
      title: "IT Professional Elective 2",
      semester: "2Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "None",
      description: "Choose from IT professional electives",
    },
    {
      code: "IT 224",
      title: "Mobile Computing",
      semester: "2Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "CC 102, IT 221",
      description: "Mobile platforms, development, and security",
    },
    {
      code: "IT 225",
      title: "Advanced Database Systems",
      semester: "2Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "CC 104",
      description: "Advanced database design and implementation techniques",
    },
    {
      code: "CW 101",
      title: "The Contemporary World",
      semester: "2Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description:
        "Globalization and its impact on individuals, communities and nations",
    },
    {
      code: "ETHICS 101",
      title: "Ethics",
      semester: "2Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description: "Principles of ethical behavior in modern society",
    },
    {
      code: "PATHFit 4",
      title:
        "Dance 2/Sports 2/Martial Arts 2/Group Exercise 2/Outdoor Activities 2",
      semester: "2Y-2S",
      units: 2,
      lec: 2,
      lab: 0,
      type: "Mandated",
      prerequisites: "PATHFit 1, PATHFit 2",
      description: "Choice-based fitness and wellness activities",
    },

    // THIRD YEAR - FIRST SEMESTER
    {
      code: "CC 105",
      title: "Application Development and Emerging Technologies",
      semester: "3Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 225",
      description: "Database management concepts, design, and implementation",
    },
    {
      code: "IT 311",
      title: "Networking 2",
      semester: "3Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 222",
      description:
        "Computer networks, network models, efficiency concepts, technologies",
    },
    {
      code: "IT 312",
      title: "Systems Integration and Architecture 1",
      semester: "3Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 221",
      description: "Integrating different systems and software applications",
    },
    {
      code: "IT Elective 3",
      title: "IT Professional Elective 3",
      semester: "3Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "None",
      description: "Choose from IT professional electives",
    },
    {
      code: "IT 314",
      title: "Data Analytics",
      semester: "3Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 212",
      description:
        "Data-driven techniques and tools for business insights and decisions",
    },

    // THIRD YEAR - SECOND SEMESTER
    {
      code: "IT 321",
      title: "Internet of Things",
      semester: "3Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "IT 311",
      description:
        "IoT concepts, technologies, sensors, actuators, embedded systems",
    },
    {
      code: "IT 322",
      title: "Machine Learning",
      semester: "3Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "IT 314",
      description:
        "Supervised/unsupervised learning, algorithms, data analysis, pattern recognition",
    },
    {
      code: "IT 323",
      title: "Information Assurance and Security 1",
      semester: "3Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 312",
      description:
        "Cyber and information security program establishment and maintenance",
    },
    {
      code: "IT Elective 4",
      title: "IT Professional Elective 4",
      semester: "3Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional Elective",
      prerequisites: "None",
      description: "Choose from IT professional electives",
    },
    {
      code: "GE Elect 3",
      title: "General Education Elective 3",
      semester: "3Y-2S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "General Education",
      prerequisites: "None",
      description: "Choose from general education electives",
    },

    // SUMMER
    {
      code: "IT 331",
      title: "Capstone Project and Research 1",
      semester: "Summer",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Professional",
      prerequisites: "Incoming 4th Year with no pending INC Grades",
      description:
        "Infrastructure, project selection, problem statement formulation, research methodology",
    },
    {
      code: "IT 332",
      title: "Information Assurance and Security 2",
      semester: "Summer",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 323",
      description:
        "Integration of confidentiality, integrity, availability through security controls",
    },

    // FOURTH YEAR - FIRST SEMESTER
    {
      code: "IT 411",
      title: "Capstone Project and Research 2",
      semester: "4Y-1S",
      units: 3,
      lec: 3,
      lab: 0,
      type: "Professional",
      prerequisites: "IT 331",
      description:
        "Infrastructure, project selection, problem statement formulation, research methodology",
    },
    {
      code: "IT 412",
      title: "Systems Administration and Maintenance",
      semester: "4Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 332",
      description: "Server configuration, system control, and maintenance",
    },
    {
      code: "IT 413",
      title: "Cybersecurity",
      semester: "4Y-1S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 332",
      description:
        "Principles, practices, threat landscapes, security policies, cryptography, incident response",
    },

    // FOURTH YEAR - SECOND SEMESTER
    {
      code: "IT 421",
      title: "Cloud Computing",
      semester: "4Y-2S",
      units: 3,
      lec: 2,
      lab: 1,
      type: "Professional",
      prerequisites: "IT 413",
      description:
        "Cloud computing principles, virtualization, distributed systems, service models",
    },
    {
      code: "IT 422",
      title: "Practicum / Industry Immersion",
      semester: "4Y-2S",
      units: 6,
      lec: 0,
      lab: 2,
      type: "Professional",
      prerequisites: "IT 411",
      description:
        "Apply knowledge in actual working environment (486 hours total)",
    },
  ],
};

export default BSIT_CURRICULUM;
